---
- name: Render mappings
  hosts: localhost
  vars:
  gather_facts: false
  tasks:
    - name: create mappings directory
      file:
        path: ../../../mappings
        state: directory

    - name: render compute mappings
      template: src=../templates/nc_mappings_compute.j2 dest=../../../mappings/rendered_mappings_compute.json

    - name: render control mappings
      template: src=../templates/nc_mappings_control.j2 dest=../../../mappings/rendered_mappings_control.json
