---
- name: run restart kubelet
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: restart kubelet for each host in region
      service:
        name: kubelet
        state: restarted
