---
- name: Remove the attributes on nodes from manifests
  hosts: all
  vars:
    cert_root: /target/certs
  gather_facts: no
  become: yes
  tasks:
    - name: Unlock /etc/kubernetes/manifests dir
      shell: "chattr -R -i /etc/kubernetes/manifests"
